SELECT
  DISTINCT(DIRECTOR.name) AS director_name
FROM
  DIRECTOR
  INNER JOIN MOVIE_DIRECTOR ON MOVIE_DIRECTOR.director_id = DIRECTOR.id
  INNER JOIN MOVIE ON MOVIE.id = MOVIE_DIRECTOR.movie_id
WHERE
  MOVIE.name LIKE "%Harry Potter%"
ORDER BY
  DIRECTOR.name ASC;
